# TSeStyleColor enum names
STYLE_COLORS = [
    "ktcBorder", "ktcCategoryButtons", "ktcCategoryPanelGroup",
    "ktcComboBox", "ktcComboBoxDisabled", "ktcButton", "ktcButtonHot",
    "ktcButtonPressed", "ktcButtonFocused", "ktcButtonDisabled",
    "ktcEdit", "ktcEditDisabled", "ktcGrid",
    "ktcGenericGradientBase", "ktcGenericGradientEnd",
    "ktcHintGradientBase", "ktcListBox", "ktcListBoxDisabled",
    "ktcListView", "ktcPanel", "ktcPanelDisabled", "ktcTreeView",
    "ktcWindow", "ktcSplitter", "ktcCategoryButtonsGradientBase",
    "ktcCategoryButtonsGradientEnd", "ktcToolBarGradientBase",
    "ktcToolBarGradientEnd", "ktcGenericBackground", "ktcHintGradientEnd",
    "ktcFocusEffect", "ktsAlternatingRowBackground",
]

# SysColors array
SYS_COLORS = [
    "clActiveBorder", "clActiveCaption", "clBtnFace", "clBtnHighlight",
    "clBtnShadow", "clBtnText", "clCaptionText", "clGrayText",
    "clHighlight", "clHighlightText", "clInactiveBorder",
    "clInactiveCaption", "clInactiveCaptionText", "clInfoBk",
    "clInfoText", "clMenu", "clMenuText", "clScrollBar",
    "cl3DDkShadow", "cl3DLight", "clWindow", "clWindowFrame",
    "clWindowText",
]

# TSeStyleFont enum names
STYLE_FONTS = [
    "ktfCaptionTextNormal", "ktfCaptionTextInactive",
    "ktfSmCaptionTextNormal", "ktfSmCaptionTextInactive",
    "ktfStaticTextNormal", "ktfStaticTextHot",
    "ktfStaticTextFocused", "ktfStaticTextDisabled",
    "ktfPanelTextNormal", "ktfPanelTextDisabled",
    "ktfButtonTextNormal", "ktfButtonTextPressed",
    "ktfButtonTextHot", "ktfButtonTextFocused",
    "ktfButtonTextDisabled", "ktfCheckBoxTextNormal",
    "ktfCheckBoxTextPressed", "ktfCheckBoxTextHot",
    "ktfCheckBoxTextFocused", "ktfCheckBoxTextDisabled",
    "ktfRadioButtonTextNormal", "ktfRadioButtonTextPressed",
    "ktfRadioButtonTextHot", "ktfRadioButtonTextFocused",
    "ktfRadioButtonTextDisabled", "ktfGroupBoxTextNormal",
    "ktfGroupBoxTextDisabled", "ktfWindowTextNormal",
    "ktfWindowTextDisabled", "ktfEditBoxTextNormal",
    "ktfEditBoxTextFocused", "ktfEditBoxTextHot",
    "ktfEditBoxTextDisabled", "ktfEditBoxTextSelected",
    "ktfMenuItemTextNormal", "ktfMenuItemTextSelected",
    "ktfMenuItemTextHot", "ktfMenuItemTextDisabled",
    "ktfToolItemTextNormal", "ktfToolItemTextSelected",
    "ktfToolItemTextHot", "ktfToolItemTextDisabled",
    "ktfHeaderSectionTextNormal", "ktfHeaderSectionTextPressed",
    "ktfHeaderSectionTextDraggedOut", "ktfHeaderSectionTextDragging",
    "ktfHeaderSectionTextHot", "ktfHeaderSectionTextUnderDrag",
    "ktfHeaderSectionTextDisabled", "ktfStatusPanelTextNormal",
    "ktfStatusPanelTextDisabled", "ktfTabTextInactiveNormal",
    "ktfTabTextInactiveHot", "ktfTabTextInactiveDisabled",
    "ktfTabTextActiveNormal", "ktfTabTextActiveHot",
    "ktfTabTextActiveDisabled", "ktfListItemTextNormal",
    "ktfListItemTextHot", "ktfListItemTextSelected",
    "ktfListItemTextFocused", "ktfListItemTextDisabled",
    "ktfPopupMenuItemTextNormal", "ktfPopupMenuItemTextSelected",
    "ktfPopupMenuItemTextHot", "ktfPopupMenuItemTextDisabled",
    "ktfCatgeoryButtonsNormal", "ktfCatgeoryButtonsHot",
    "ktfCatgeoryButtonsSelected", "ktfCatgeoryButtonsCategoryNormal",
    "ktfCatgeoryButtonsCategorySelected",
    "ktfCategoryPanelGroupHeaderNormal",
    "ktfCategoryPanelGroupHeaderHot", "ktfComboBoxItemNormal",
    "ktfComboBoxItemFocused", "ktfComboBoxItemHot",
    "ktfComboBoxItemDisabled", "ktfComboBoxItemSelected",
    "ktfGridItemNormal", "ktfGridItemSelected",
    "ktfGridItemFixedNormal", "ktfGridItemFixedHot",
    "ktfGridItemFixedPressed", "ktfTreeItemTextNormal",
    "ktfTreeItemTextHot", "ktfTreeItemTextSelected",
    "ktfTreeItemTextFocused", "ktfTreeItemTextDisabled",
]

NAMED_COLORS = {
    "clBlack":   "#000000",
    "clMaroon":  "#800000",
    "clGreen":   "#008000",
    "clOlive":   "#808000",
    "clNavy":    "#000080",
    "clPurple":  "#800080",
    "clTeal":    "#008080",
    "clGray":    "#808080",
    "clSilver":  "#c0c0c0",
    "clRed":     "#ff0000",
    "clLime":    "#00ff00",
    "clYellow":  "#ffff00",
    "clBlue":    "#0000ff",
    "clFuchsia": "#ff00ff",
    "clAqua":    "#00ffff",
    "clWhite":   "#ffffff",
    "clNone":    "#000000",
}

VSF_HEADER = b"VCL_STYLE 1.0"
OBJECT_FLAG = 0xF0000
